# Generated by Django 4.0.3 on 2022-07-20 14:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('ultimo_login', models.DateTimeField(auto_now=True, verbose_name='Último Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rh', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_interno', models.BooleanField(default=False)),
                ('is_gestor', models.BooleanField(default=False)),
                ('is_diretor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=64, verbose_name='Cargo')),
                ('descricao_cargo', models.CharField(blank=True, max_length=64, null=True, verbose_name='Descrição Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cadastros de Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Cidade')),
                ('state_code', models.CharField(max_length=255, verbose_name='Cod Estado')),
                ('country_code', models.CharField(max_length=255, verbose_name='Cod Pais')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(verbose_name='Data Criacao')),
                ('updated_at', models.DateTimeField(verbose_name='Data Modificacao')),
                ('flag', models.BooleanField(default=True, verbose_name='Flag')),
                ('wikiDataId', models.CharField(max_length=255, null=True, verbose_name='WikiDataId')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=128, verbose_name='Fase')),
                ('descricao_fase', models.TextField(blank=True, null=True, verbose_name='Descrição Fase')),
            ],
            options={
                'verbose_name': 'Fases',
                'verbose_name_plural': 'Cadastros de Fases',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('razao', models.CharField(max_length=191)),
                ('cnpj', models.CharField(max_length=32)),
                ('cidade', models.CharField(max_length=32)),
                ('endereco', models.CharField(max_length=191)),
                ('cep', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=32)),
                ('grupo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=32)),
                ('grupo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pais')),
                ('iso3', models.CharField(max_length=255, verbose_name='ISO3')),
                ('numeric_code', models.IntegerField(verbose_name='Codigo')),
                ('iso2', models.CharField(max_length=255, verbose_name='ISO2')),
                ('phonecode', models.CharField(max_length=191, verbose_name='Código Postal')),
                ('capital', models.CharField(max_length=255, verbose_name='Capital')),
                ('currency', models.CharField(max_length=255, verbose_name='Moeda')),
                ('currency_name', models.CharField(max_length=255, verbose_name='Nome da Moeda')),
                ('currency_symbol', models.CharField(max_length=255, verbose_name='Simbolo da Moeda')),
                ('tld', models.CharField(max_length=255)),
                ('native', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=255, verbose_name='Regiao')),
                ('subregion', models.CharField(max_length=255, verbose_name='Subregiao')),
                ('timezones', models.TextField()),
                ('translations', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitude')),
                ('emoji', models.CharField(max_length=191, verbose_name='emoji')),
                ('emojiU', models.CharField(max_length=191, verbose_name='emojiU')),
                ('created_at', models.DateTimeField(verbose_name='Data Criacao')),
                ('updated_at', models.DateTimeField(verbose_name='Data Modificacao')),
                ('flag', models.BooleanField(default=True, verbose_name='Flag')),
                ('wikiDataId', models.CharField(max_length=255, null=True, verbose_name='WikiDataId')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=64, verbose_name='Setor')),
                ('descricao_setor', models.CharField(blank=True, max_length=64, null=True, verbose_name='Descrição Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Cadastros de Setores',
            },
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=32)),
                ('grupo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vaga', models.IntegerField(unique=True, verbose_name='Código da Vaga')),
                ('status_vaga', models.BooleanField(default=True, verbose_name='Status da Vaga')),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], max_length=32, verbose_name='Urgência da Vaga')),
                ('data_validade', models.DateField(verbose_name='Data de Encerramento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Vagas')),
                ('jornada', models.CharField(default='07:30 às 17:30', max_length=32, verbose_name='Jornada de Trabalho')),
                ('ensino', models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Técnico', 'Ensino Técnico'), ('Ensino Superior', 'Ensino Superior'), ('Pós Graduação', 'Pós Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=32, verbose_name='Nível de Escolaridade')),
                ('contratacao', models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('CLT', 'CLT'), ('Estágio', 'Estágio'), ('Temporario', 'Temporario')], max_length=32, verbose_name='Tipo de Contratação')),
                ('atividades', ckeditor.fields.RichTextField(max_length=1024, verbose_name='Principais Atividades')),
                ('qualificacao', ckeditor.fields.RichTextField(max_length=1024, verbose_name='Requisitos')),
                ('descricao', ckeditor.fields.RichTextField(max_length=1024, verbose_name='Observações')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargos', verbose_name='Cargo')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filial', verbose_name='Filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.setores', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Cadastro de Vagas',
            },
        ),
        migrations.CreateModel(
            name='VagasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cadastro', models.BooleanField(default=False, verbose_name='Status de Cadastro')),
                ('pontuacao_vaga', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pontuacao da Vaga')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vagas')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Apuração de Cadastros',
            },
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_termo', models.BooleanField(default=True, verbose_name='Status do Termo')),
                ('data_termo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Aceite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade e Condição de Uso',
                'verbose_name_plural': 'Termos de Responsabilidade e Condição de Uso',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_tecnologia_usuario', to='main.niveis')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologia_usuario', to='main.tecnologias')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conhecimento Tecnológico do Usuário',
                'verbose_name_plural': 'Conhecimentos Tecnológico',
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('ensino', models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Técnico', 'Ensino Técnico'), ('Ensino Superior', 'Ensino Superior'), ('Pós Graduação', 'Pós Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=32)),
                ('tipo', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=32)),
                ('tipo_vaga', models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('CLT', 'CLT'), ('Estágio', 'Estágio'), ('Temporario', 'Temporario')], max_length=32)),
                ('requisitos', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True)),
                ('atividades', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True)),
                ('habilidades', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True)),
                ('ferramentas', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True)),
                ('recrutamento', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True)),
                ('informacoes', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True)),
                ('status_a', models.BooleanField(default=True)),
                ('data_a', models.DateField(auto_now_add=True)),
                ('status_b', models.BooleanField(blank=True, default=False, null=True)),
                ('data_b', models.DateField(blank=True, null=True)),
                ('status_c', models.BooleanField(default=False)),
                ('data_c', models.DateField(blank=True, null=True)),
                ('status_d', models.BooleanField(default=False)),
                ('data_d', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargos')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filial')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestor', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.setores')),
                ('usuario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_a', to=settings.AUTH_USER_MODEL)),
                ('usuario_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_b', to=settings.AUTH_USER_MODEL)),
                ('usuario_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_c', to=settings.AUTH_USER_MODEL)),
                ('usuario_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisição de Vaga',
                'verbose_name_plural': 'Requisições de Vagas',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta1', models.TextField(verbose_name='Descreva como é um bom lugar para se trabalhar')),
                ('pergunta2', models.TextField(verbose_name='Você prefere trabalhar sozinho ou em equipe?')),
                ('pergunta3', models.TextField(verbose_name='Qual foi sua maior conquista até hoje (pessoal ou profissional)?')),
                ('pergunta4', models.TextField(verbose_name='Qual o seu maior sonho?')),
                ('pergunta5', models.TextField(verbose_name='Por que deseja trabalhar conosco?')),
                ('pontuacao_questionario', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pontuacao do Questionário')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro do Questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Apuração de Questionários',
            },
        ),
        migrations.CreateModel(
            name='ImagensPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=main.models.local_upload, verbose_name='Alterar Imagem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem de Perfil',
                'verbose_name_plural': 'Imagens de Perfil',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idioma_usuario', to='main.idiomas')),
                ('nivel_idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_idioma_usuario', to='main.niveis')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idiomas do Usuário',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridade', models.CharField(blank=True, choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Técnico', 'Ensino Técnico'), ('Ensino Superior', 'Ensino Superior'), ('Pós Graduação', 'Pós Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=32, null=True, verbose_name='Nível de Escolaridade')),
                ('instituicao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de Ensino')),
                ('curso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Curso')),
                ('status_formacao', models.CharField(blank=True, choices=[('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Trancado', 'Trancado')], max_length=32, null=True, verbose_name='Status')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formações Acadêmcias do Usuário',
                'verbose_name_plural': 'Formações Acadêmcias',
            },
        ),
        migrations.CreateModel(
            name='FaseUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', ckeditor.fields.RichTextField(blank=True, max_length=10240, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro da Fase')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fase', verbose_name='Fase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vagas', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Fase do Processo',
                'verbose_name_plural': 'Fases dos Processos',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organização')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('cargo_exp', models.TextField(blank=True, null=True, verbose_name='Cargo')),
                ('atividades_exp', models.TextField(blank=True, null=True, verbose_name='Atvididades')),
                ('atuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.setores', verbose_name='Area de Atuação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiências Profissional do Usuário',
                'verbose_name_plural': 'Experiências Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Cidade')),
                ('country_code', models.CharField(max_length=255, verbose_name='Cod Pais')),
                ('fips_code', models.CharField(max_length=255, null=True, verbose_name='FIPS')),
                ('iso2', models.CharField(max_length=255, verbose_name='ISO2')),
                ('typ', models.CharField(max_length=191, null=True, verbose_name='Type')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(verbose_name='Data Criacao')),
                ('updated_at', models.DateTimeField(verbose_name='Data Modificacao')),
                ('flag', models.BooleanField(default=True, verbose_name='Flag')),
                ('wikiDataId', models.CharField(max_length=255, null=True, verbose_name='WikiDataId')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paises')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('cpf', models.CharField(max_length=32, verbose_name='CPF')),
                ('rg', models.CharField(max_length=32, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Prefiro não declarar', 'Prefiro não declarar')], max_length=32, verbose_name='Gênero')),
                ('estado_civil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=32, verbose_name='Estado Civil')),
                ('cep', models.CharField(max_length=32, verbose_name='Código Postal')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=32, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('telefone', models.CharField(blank=True, max_length=32, null=True)),
                ('celular', models.CharField(max_length=32)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro do Currículo')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cidades')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estados')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paises')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='Complementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_emprego', models.BooleanField(default=False, verbose_name='Primeiro Emprego')),
                ('deficiencia', models.BooleanField(default=False, verbose_name='Possuo Deficiência')),
                ('disponivel_viagem', models.BooleanField(default=False, verbose_name='Disponível para Viagem')),
                ('pretensao', models.CharField(blank=True, max_length=32, null=True, verbose_name='Pretensão Salarial')),
                ('cnh', models.CharField(choices=[('Não Possuo', 'Não Possuo'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=32, verbose_name='CNH')),
                ('inspecao', models.CharField(choices=[('Facebook', 'Facebook'), ('Indicação', 'Indicação'), ('LinkedIn', 'LinkedIn'), ('Site', 'Site'), ('Outros', 'Outros')], max_length=32, verbose_name='Como Nos Conheceu')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn')),
                ('distancia', models.CharField(choices=[('50km ou menos', '50km ou menos'), ('50km - 100km', '50km - 100km'), ('100km - 150km', '100km - 150km'), ('150km - 200km', '150km - 200km'), ('200km ou mais', '200km ou mais')], max_length=32, verbose_name='Qual a distância entre você e nossa matriz?')),
                ('interesse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_interesse', to='main.setores', verbose_name='Área de Interesse (1)')),
                ('interesse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_interesse', to='main.setores', verbose_name='Área de Interesse (2)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dados Complementares do Usuário',
                'verbose_name_plural': 'Dados Complementares',
            },
        ),
        migrations.AddField(
            model_name='cidades',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paises'),
        ),
        migrations.AddField(
            model_name='cidades',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estados'),
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.FileField(blank=True, null=True, upload_to=main.models.doc_upload, verbose_name='Documentos')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio dos Documentos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Apuração de Documentos',
            },
        ),
    ]
