# Generated by Django 4.0.3 on 2022-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='tipo',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo'), ('Interno/Externo', 'Interno/Externo')], max_length=32),
        ),
    ]
