# Generated by Django 4.0.3 on 2022-07-28 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_requisicao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='usuario_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='usuario_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_humanos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='usuario_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='usuario_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL),
        ),
    ]
